### Numpy中常用的统计方法

In [3]:
# 以下所有函数都接受ndarray和axis。axis为？，那一维就会消失
np.sum()
np.mean() #平均值
np.median() # 中值
np.max()
np.min()
np.ptp() # 极值（最大值和最小值之差）
np.std() # 标准差

In [1]:
import numpy as np

### 数据的拼接

In [ ]:
# 竖直拼接 (在每一列拼接)
np.vstack()
# 水平拼接（在每一行拼接）
np.hstack()

In [10]:
a = np.arange(20).reshape(4,5)
b = np.arange(100,120).reshape(4,5)
print("vstack:")
print(np.vstack((a,b)))
print("hstack:")
print(np.hstack((a,b)))

vstack:
[[  0   1   2   3   4]
 [  5   6   7   8   9]
 [ 10  11  12  13  14]
 [ 15  16  17  18  19]
 [100 101 102 103 104]
 [105 106 107 108 109]
 [110 111 112 113 114]
 [115 116 117 118 119]]
hstack:
[[  0   1   2   3   4 100 101 102 103 104]
 [  5   6   7   8   9 105 106 107 108 109]
 [ 10  11  12  13  14 110 111 112 113 114]
 [ 15  16  17  18  19 115 116 117 118 119]]


### 行交换和列交换

In [15]:
a = np.arange(20).reshape(4,5)
print(a)
a[[1,2],:]=a[[2,1],:] #交换第二行和第三行
print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[[ 0  1  2  3  4]
 [10 11 12 13 14]
 [ 5  6  7  8  9]
 [15 16 17 18 19]]


In [16]:
a = np.arange(20).reshape(4,5)
print(a)
a[:,[1,2]]=a[:,[2,1]] #交换第二列和第三列
print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[[ 0  2  1  3  4]
 [ 5  7  6  8  9]
 [10 12 11 13 14]
 [15 17 16 18 19]]


### Numpy中的常用方法

In [17]:
# 获取最大最小值的位置
np.argmax()
np.argmin()
# 创建一个全为0的数组
np.zeros()
# 创建一个全为1的数组
np.ones()
# 创建一个n阶单位矩阵
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### Numpy中的随机函数

In [19]:
np.random.rand(2,3) # 均匀分布 取值[0,1)
np.random.randn(2,3) # 标准正态分布

array([[-0.20297766,  0.35130334, -0.08313328],
       [-0.12909576, -0.07793512,  0.10717606]])

In [20]:
np.random.uniform(0,10,(2,3))
np.random.normal(0,0.1,(2,3))

array([[ 0.09601934, -0.09827707,  0.01400063],
       [-0.30715488,  0.06709224,  0.149689  ]])

In [23]:
# 随机种子，指定后每次产生的随机数都相同
np.random.seed(10)

### 复制和视图
- a = b  
完全不复制
- a = b[:]  
视图，前面交换两列用到了，创建新的对象但相互影响
- a = b.copy()  
复制，a、b互不影响